-- begin AJJFTEST_DOJO
alter table AJJFTEST_DOJO add constraint FK_AJJFTEST_DOJO_ON_HEAD1 foreign key (HEAD1_ID) references AJJFTEST_MEMBER(ID)^
alter table AJJFTEST_DOJO add constraint FK_AJJFTEST_DOJO_ON_HEAD2 foreign key (HEAD2_ID) references AJJFTEST_MEMBER(ID)^
alter table AJJFTEST_DOJO add constraint FK_AJJFTEST_DOJO_ON_HEAD3 foreign key (HEAD3_ID) references AJJFTEST_MEMBER(ID)^
create index IDX_AJJFTEST_DOJO_ON_HEAD1 on AJJFTEST_DOJO (HEAD1_ID)^
create index IDX_AJJFTEST_DOJO_ON_HEAD2 on AJJFTEST_DOJO (HEAD2_ID)^
create index IDX_AJJFTEST_DOJO_ON_HEAD3 on AJJFTEST_DOJO (HEAD3_ID)^
-- end AJJFTEST_DOJO
-- begin AJJFTEST_MEMBER
alter table AJJFTEST_MEMBER add constraint FK_AJJFTEST_MEMBER_ON_DOJO foreign key (DOJO_ID) references AJJFTEST_DOJO(ID)^
alter table AJJFTEST_MEMBER add constraint FK_AJJFTEST_MEMBER_ON_RANK foreign key (RANK_ID) references AJJFTEST_CODES_RANK(ID)^
create index IDX_AJJFTEST_MEMBER_ON_DOJO on AJJFTEST_MEMBER (DOJO_ID)^
create index IDX_AJJFTEST_MEMBER_ON_RANK on AJJFTEST_MEMBER (RANK_ID)^
-- end AJJFTEST_MEMBER
-- begin AJJFTEST_RENEWAL_HISTORY
alter table AJJFTEST_RENEWAL_HISTORY add constraint FK_AJJFTEST_RENEWAL_HISTORY_MEMBER foreign key (MEMBER_ID) references AJJFTEST_MEMBER(ID)^
create index IDX_AJJFTEST_RENEWAL_HISTORY_MEMBER on AJJFTEST_RENEWAL_HISTORY (MEMBER_ID)^
-- end AJJFTEST_RENEWAL_HISTORY
-- begin AJJFTEST_RANK_HISTORY
alter table AJJFTEST_RANK_HISTORY add constraint FK_AJJFTEST_RANK_HISTORY_NEW_RANK foreign key (NEW_RANK_ID) references AJJFTEST_CODES_RANK(ID)^
alter table AJJFTEST_RANK_HISTORY add constraint FK_AJJFTEST_RANK_HISTORY_EXAMINER1 foreign key (EXAMINER1_ID) references AJJFTEST_MEMBER(ID)^
alter table AJJFTEST_RANK_HISTORY add constraint FK_AJJFTEST_RANK_HISTORY_EXAMINER2 foreign key (EXAMINER2_ID) references AJJFTEST_MEMBER(ID)^
alter table AJJFTEST_RANK_HISTORY add constraint FK_AJJFTEST_RANK_HISTORY_EXAMINER3 foreign key (EXAMINER3_ID) references AJJFTEST_MEMBER(ID)^
alter table AJJFTEST_RANK_HISTORY add constraint FK_AJJFTEST_RANK_HISTORY_EXAMINER4 foreign key (EXAMINER4_ID) references AJJFTEST_MEMBER(ID)^
alter table AJJFTEST_RANK_HISTORY add constraint FK_AJJFTEST_RANK_HISTORY_CALLER foreign key (CALLER_ID) references AJJFTEST_MEMBER(ID)^
alter table AJJFTEST_RANK_HISTORY add constraint FK_AJJFTEST_RANK_HISTORY_MEMBER foreign key (MEMBER_ID) references AJJFTEST_MEMBER(ID)^
create index IDX_AJJFTEST_RANK_HISTORY_NEW_RANK on AJJFTEST_RANK_HISTORY (NEW_RANK_ID)^
create index IDX_AJJFTEST_RANK_HISTORY_EXAMINER1 on AJJFTEST_RANK_HISTORY (EXAMINER1_ID)^
create index IDX_AJJFTEST_RANK_HISTORY_EXAMINER2 on AJJFTEST_RANK_HISTORY (EXAMINER2_ID)^
create index IDX_AJJFTEST_RANK_HISTORY_EXAMINER3 on AJJFTEST_RANK_HISTORY (EXAMINER3_ID)^
create index IDX_AJJFTEST_RANK_HISTORY_EXAMINER4 on AJJFTEST_RANK_HISTORY (EXAMINER4_ID)^
create index IDX_AJJFTEST_RANK_HISTORY_CALLER on AJJFTEST_RANK_HISTORY (CALLER_ID)^
create index IDX_AJJFTEST_RANK_HISTORY_MEMBER on AJJFTEST_RANK_HISTORY (MEMBER_ID)^
-- end AJJFTEST_RANK_HISTORY
-- begin AJJFTEST_TEMPLATE
create unique index IDX_AJJFTEST_TEMPLATE_UNIQ_NAME on AJJFTEST_TEMPLATE (NAME) ^
-- end AJJFTEST_TEMPLATE
-- begin AJJFTEST_CENTRAL_OFFICE
create unique index IDX_AJJFTEST_CENTRAL_OFFICE_UNIQ_ORG_ID on AJJFTEST_CENTRAL_OFFICE (ORG_ID) ^
-- end AJJFTEST_CENTRAL_OFFICE
