alter table AJJFTEST_RANK_HISTORY add constraint FK_AJJFTEST_RANK_HISTORY_MEMBER foreign key (MEMBER_ID) references AJJFTEST_MEMBER(ID);
create index IDX_AJJFTEST_RANK_HISTORY_MEMBER on AJJFTEST_RANK_HISTORY (MEMBER_ID);
