alter table AJJFTEST_RANK_HISTORY add constraint FK_AJJFTEST_RANK_HISTORY_EXAMINER4 foreign key (EXAMINER4_ID) references AJJFTEST_MEMBER(ID);
create index IDX_AJJFTEST_RANK_HISTORY_EXAMINER4 on AJJFTEST_RANK_HISTORY (EXAMINER4_ID);
