alter table AJJFTEST_MEMBER add constraint FK_AJJFTEST_MEMBER_RANK_HISTORY foreign key (RANK_HISTORY_ID) references AJJFTEST_RANK_HISTORY(ID);
create index IDX_AJJFTEST_MEMBER_RANK_HISTORY on AJJFTEST_MEMBER (RANK_HISTORY_ID);
