alter table AJJFTEST_RENEWAL_HISTORY add constraint FK_AJJFTEST_RENEWAL_HISTORY_MEMBER foreign key (MEMBER_ID) references AJJFTEST_MEMBER(ID);
create index IDX_AJJFTEST_RENEWAL_HISTORY_MEMBER on AJJFTEST_RENEWAL_HISTORY (MEMBER_ID);
