alter table AJJFTEST_RANK_HISTORY add constraint FK_AJJFTEST_RANK_HISTORY_EXAMINER3 foreign key (EXAMINER3_ID) references AJJFTEST_MEMBER(ID);
create index IDX_AJJFTEST_RANK_HISTORY_EXAMINER3 on AJJFTEST_RANK_HISTORY (EXAMINER3_ID);
