alter table AJJFTEST_MEMBER add constraint FK_AJJFTEST_MEMBER_MEMBER_TRANS foreign key (MEMBER_TRANS_ID) references AJJFTEST_MEMBER_TRANS(ID);
create index IDX_AJJFTEST_MEMBER_MEMBER_TRANS on AJJFTEST_MEMBER (MEMBER_TRANS_ID);
