alter table AJJFTEST_RANK_HISTORY add constraint FK_AJJFTEST_RANK_HISTORY_NEW_RANK foreign key (NEW_RANK_ID) references AJJFTEST_CODES_RANK(ID);
create index IDX_AJJFTEST_RANK_HISTORY_NEW_RANK on AJJFTEST_RANK_HISTORY (NEW_RANK_ID);
