alter table AJJFTEST_RANK_HISTORY add constraint FK_AJJFTEST_RANK_HISTORY_EXAMINER1 foreign key (EXAMINER1_ID) references AJJFTEST_MEMBER(ID);
create index IDX_AJJFTEST_RANK_HISTORY_EXAMINER1 on AJJFTEST_RANK_HISTORY (EXAMINER1_ID);
